name: newproject
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  cupertino_icons: ^1.0.2
  readmore: ^2.2.0 # <== dépendance à ajouter

flutter:
  uses-material-design: true


assets:
  - assets/images/
